In [2]:
import pandas as pd

salary = pd.read_csv('Salary.csv')
print(salary.head())

   YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891


In [3]:
# train/test 분리 
# 변수 스케일링 
# 모델 정의
# 학습 
# 예측 
# score
# 그래프 그려보기 

In [4]:
# x, y 분리하기 

x = salary.iloc[:,0].values
y = salary.iloc[:,1].values

print(x)
print(y)



[ 1.1  1.3  1.5  2.   2.2  2.9  3.   3.2  3.2  3.7  3.9  4.   4.   4.1
  4.5  4.9  5.1  5.3  5.9  6.   6.8  7.1  7.9  8.2  8.7  9.   9.5  9.6
 10.3 10.5 11.2 11.5 12.3 12.9 13.5]
[ 39343  46205  37731  43525  39891  56642  60150  54445  64445  57189
  63218  55794  56957  57081  61111  67938  66029  83088  81363  93940
  91738  98273 101302 113812 109431 105582 116969 112635 122391 121872
 127345 126756 128765 135675 139465]


In [5]:
# reshape 

x = x.reshape(-1,1)
y = y.reshape(-1,1)
print(x,y)

[[ 1.1]
 [ 1.3]
 [ 1.5]
 [ 2. ]
 [ 2.2]
 [ 2.9]
 [ 3. ]
 [ 3.2]
 [ 3.2]
 [ 3.7]
 [ 3.9]
 [ 4. ]
 [ 4. ]
 [ 4.1]
 [ 4.5]
 [ 4.9]
 [ 5.1]
 [ 5.3]
 [ 5.9]
 [ 6. ]
 [ 6.8]
 [ 7.1]
 [ 7.9]
 [ 8.2]
 [ 8.7]
 [ 9. ]
 [ 9.5]
 [ 9.6]
 [10.3]
 [10.5]
 [11.2]
 [11.5]
 [12.3]
 [12.9]
 [13.5]] [[ 39343]
 [ 46205]
 [ 37731]
 [ 43525]
 [ 39891]
 [ 56642]
 [ 60150]
 [ 54445]
 [ 64445]
 [ 57189]
 [ 63218]
 [ 55794]
 [ 56957]
 [ 57081]
 [ 61111]
 [ 67938]
 [ 66029]
 [ 83088]
 [ 81363]
 [ 93940]
 [ 91738]
 [ 98273]
 [101302]
 [113812]
 [109431]
 [105582]
 [116969]
 [112635]
 [122391]
 [121872]
 [127345]
 [126756]
 [128765]
 [135675]
 [139465]]


In [8]:
# 변수 스케일링 
# 변수 범위와 스케일이 많이 다르니 조절하기 
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaled_x = scaler.fit_transform(x)
scaled_y = scaler.fit_transform(y)

print(scaled_x, scaled_y)


[[0.        ]
 [0.01612903]
 [0.03225806]
 [0.07258065]
 [0.08870968]
 [0.14516129]
 [0.15322581]
 [0.16935484]
 [0.16935484]
 [0.20967742]
 [0.22580645]
 [0.23387097]
 [0.23387097]
 [0.24193548]
 [0.27419355]
 [0.30645161]
 [0.32258065]
 [0.33870968]
 [0.38709677]
 [0.39516129]
 [0.45967742]
 [0.48387097]
 [0.5483871 ]
 [0.57258065]
 [0.61290323]
 [0.63709677]
 [0.67741935]
 [0.68548387]
 [0.74193548]
 [0.75806452]
 [0.81451613]
 [0.83870968]
 [0.90322581]
 [0.9516129 ]
 [1.        ]] [[0.01584524]
 [0.08329565]
 [0.        ]
 [0.05695244]
 [0.02123184]
 [0.18588672]
 [0.2203688 ]
 [0.16429119]
 [0.26258675]
 [0.19126349]
 [0.25052588]
 [0.17755126]
 [0.18898303]
 [0.1902019 ]
 [0.22981501]
 [0.29692138]
 [0.27815676]
 [0.44583915]
 [0.42888317]
 [0.55250949]
 [0.5308648 ]
 [0.59510095]
 [0.62487467]
 [0.74784241]
 [0.70477913]
 [0.66694517]
 [0.77887432]
 [0.73627303]
 [0.83217017]
 [0.82706863]
 [0.88086579]
 [0.87507618]
 [0.89482376]
 [0.96274598]
 [1.        ]]


In [9]:
# train/test 분리 

from sklearn.model_selection import train_test_split

train_x, test_x, train_y, test_y = train_test_split(scaled_x,scaled_y,test_size = 0.2, random_state= 123)

print(train_x.shape)
print(test_x.shape)
print(train_y.shape)
print(test_x.shape)

# 아 2차원으로 만드는것을 까먹음 다시! 

(28, 1)
(7, 1)
(28, 1)
(7, 1)


In [10]:
# 모델 정의
# 선형회귀모델 

from sklearn.linear_model import LinearRegression

model = LinearRegression()

In [11]:
# 학습

model.fit(train_x,train_y)

LinearRegression()

In [13]:
# 예측
y_pred = model.predict(test_x)
print(y_pred)

[[0.16378936]
 [0.8706569 ]
 [0.15516902]
 [0.24999271]
 [0.6551485 ]
 [0.18103003]
 [0.81031454]]


In [17]:
# score 
model.score(test_x, test_y)

0.9718258684251991

In [19]:
# 손실값 계산 
from sklearn.metrics import mean_squared_error
loss = mean_squared_error(test_y, y_pred)
print(loss)

0.0024809444622259373


In [26]:
# 아이리스 꽃 분류 

import numpy as np

# 필수 라이브러리 외워두기 
# 학습/테스트데이터 분리하기 
from sklearn.model_selection import train_test_split
# 대표적인 데이터를 불러오는 라이브러리
from sklearn.datasets import load_iris
# 선형회귀모델(로지스틱회귀는 분류이지만 선형회귀모델안에 속해있다.) 
from sklearn.linear_model import LogisticRegression
# 손실값 구할때! 
from sklearn.metrics import log_loss, accuracy_score, f1_score, precision_score, recall_score

# 데이터 불러오기 + 분할 
data = load_iris()
X = data.data
y = data.target
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.2, random_state=42)

# 모델 정의 및 학습
model = LogisticRegression(max_iter=200)
model.fit(train_X, train_y)

# 예측값 생성
y_pred = model.predict(test_X)
y_pred_proba = model.predict_proba(test_X)
print(y_pred_proba)

# 손실값 계산 (Log Loss)
loss = log_loss(test_y, y_pred_proba)
print(f"Log Loss: {loss}")

# 모델 성능 평가 (정확도)
accuracy = accuracy_score(test_y, y_pred)
print(f"Accuracy: {accuracy}")

# F1 스코어 계산 (다중 클래스의 경우 weighted 평균)
f1 = f1_score(test_y, y_pred, average='weighted')
print(f"F1 Score (weighted): {f1}")

# precision
precision = precision_score(test_y, y_pred, average='weighted')
print(f"precision Score : {precision}")

# recall
recall = precision_score(test_y, y_pred, average='weighted')
print(f"recall Score : {recall}")

[[3.80366675e-03 8.27739542e-01 1.68456791e-01]
 [9.46969747e-01 5.30300543e-02 1.98774873e-07]
 [8.86029729e-09 1.54854019e-03 9.98451451e-01]
 [6.48546697e-03 7.92228600e-01 2.01285933e-01]
 [1.45768003e-03 7.74128412e-01 2.24413908e-01]
 [9.55899676e-01 4.41001477e-02 1.76045334e-07]
 [7.80156868e-02 9.07701293e-01 1.42830204e-02]
 [1.63870749e-04 1.54555675e-01 8.45280454e-01]
 [2.22394473e-03 7.62851513e-01 2.34924542e-01]
 [2.84394195e-02 9.45735859e-01 2.58247218e-02]
 [4.45484058e-04 2.42557408e-01 7.56997108e-01]
 [9.68124830e-01 3.18750918e-02 7.79534105e-08]
 [9.73005359e-01 2.69946077e-02 3.31820454e-08]
 [9.61905950e-01 3.80939389e-02 1.10700557e-07]
 [9.79285388e-01 2.07145477e-02 6.44550338e-08]
 [4.59483811e-03 7.12372778e-01 2.83032384e-01]
 [7.31656392e-06 2.41374502e-02 9.75855233e-01]
 [2.73617560e-02 9.47767057e-01 2.48711867e-02]
 [8.26145678e-03 8.31673616e-01 1.60064927e-01]
 [1.43613957e-05 3.58380620e-02 9.64147577e-01]
 [9.64169177e-01 3.58306302e-02 1.925030

In [34]:
# 아이리스 꽃 분류 

import numpy as np

# 필수 라이브러리 외워두기 
# 학습/테스트데이터 분리하기 
from sklearn.model_selection import train_test_split
# 대표적인 데이터를 불러오는 라이브러리
from sklearn.datasets import load_iris
# 랜덤포레스트 
from sklearn.ensemble import RandomForestClassifier
# 손실값 구할때! 
from sklearn.metrics import log_loss, accuracy_score, f1_score, precision_score, recall_score

# 데이터 불러오기 + 분할 
data = load_iris()
print(data)
X = data.data
y = data.target
# print(X)
# print(y)
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.2, random_state=42)

# 모델 정의 및 학습
# model = LogisticRegression(max_iter=200)
model = RandomForestClassifier()
model.fit(train_X, train_y)

# 예측값 생성
y_pred = model.predict(test_X)
y_pred_proba = model.predict_proba(test_X)
# print(y_pred_proba)

# 손실값 계산 (Log Loss)
loss = log_loss(test_y, y_pred_proba)
print(f"Log Loss: {loss}")

# 모델 성능 평가 (정확도)
accuracy = accuracy_score(test_y, y_pred)
print(f"Accuracy: {accuracy}")

# F1 스코어 계산 (다중 클래스의 경우 weighted 평균)
f1 = f1_score(test_y, y_pred, average='weighted')
print(f"F1 Score (weighted): {f1}")

# precision
precision = precision_score(test_y, y_pred, average='weighted')
print(f"precision Score : {precision}")

# recall
recall = precision_score(test_y, y_pred, average='weighted')
print(f"recall Score : {recall}")

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [ ]:
# 그리드 서치 

from sklearn.model_selection import GridSearchCV

# grid_search = GridSearchCV(
#     estimator=rf_model,       # 사용할 모델
#     param_grid=param_grid,    # 하이퍼파라미터 그리드
#     cv=3,                     # 3-fold 교차 검증
#     n_jobs=-1,                # 병렬 처리: 모든 CPU 코어 사용
#     verbose=2                 # 출력 상세도: 2
# )

