## 1. Numpy import 하기

In [3]:
# numpy패키지를 np라는 별칭으로 가져와서 사용한다.
import numpy as np

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
# import한 패키지의 별칭만 다르게 사용하면
# 모든 파이썬 패키지의 버전을 확인할수 있다.
print(np.__version__)

1.26.4


In [5]:
# !는 리눅스 터미널 명령어를 사용할때 붙이는 기호
!pip list

Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
accelerate                       0.32.1
aiohappyeyeballs                 2.3.4
aiohttp                          3.10.0
aiosignal                        1.3.1
alabaster                        0.7.16
albucore                         0.0.13
albumentations                   1.4.12
altair                           4.2.2
annotated-types                  0.7.0
anyio                            3.7.1
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array_record                     0.5.1
arviz                            0.18.0
asn1crypto                       1.5.1
astropy                          6.1.2
astropy-iers-data                0.2024.7.29.0.32.7
astunparse                       1.6.3
async-timeout                    4.0.3
atpublic                         4.1.0
attrs                            23.2.0
audioread               

## 2. ndarray 생성하기

In [ ]:
arr = np.array([1, 2, 3, 4], dtype=int)

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr0 = np.array([1.,2.,3.,4.])
type(arr0)

numpy.ndarray

### 2-1. list로 부터 생성하기

In [ ]:
mylist1 = [1, 2, 3, 4]

In [ ]:
mylist2 = [[1, 2, 3, 4],
           [5, 6, 7, 8]]

In [ ]:
arr1 = np.array(mylist1)

In [ ]:
arr2 = np.array(mylist2)

### 2-2. shape확인하기

In [ ]:
# 4행으로 만들어진 array
arr1.shape

(4,)

In [ ]:
arr2.shape

(2, 4)

## 3. array에서의 data 타입

array에서는 list와는 다르게 1개의 **단일 데이터 타입**만 허용

### 3-1. list에서의 data 타입

In [ ]:
mylist = [1, 3.14, 'hello', '1234']

In [ ]:
mylist

[1, 3.14, 'hello', '1234']

In [ ]:
mylist[1]

3.14

In [ ]:
mylist[2]

'hello'

### 3-2. array에서의 data 타입이 혼재된 경우

### int와 float 타입이 섞인 경우

In [ ]:
arr = np.array([1, 2, 3, 3.14])

In [ ]:
arr

array([1.  , 2.  , 3.  , 3.14])

### int와 float 타입이 섞인 경우, dtype을 지정한 경우

In [ ]:
arr = np.array([1, 2, 3, 3.14], dtype=int)

In [ ]:
arr

array([1, 2, 3, 3])

### int와 float, str 타입이 혼재된 경우

In [ ]:
arr = np.array([1, 3.14, 'abc', '1234'])

In [ ]:
arr

array(['1', '3.14', 'abc', '1234'], dtype='<U32')

In [ ]:
arr[0] + arr[1]

'13.14'

### int와 str 타입이 혼재된 경우, int로 dtype을 지정한 경우

In [ ]:
temp = '1234'
value = int(temp)
type(value)

int

In [ ]:
arr = np.array([1, 3.14, '1234'], dtype=int)

In [ ]:
    arr

array([   1,    3, 1234])