In [1]:
import numpy as np

## 1. 슬라이싱 (Slicing)

배열의 부분 선택 (잘라내기)

In [2]:
# python에서 숫자의 범위 0~9(10미만)
temp = range(10)
temp
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
# python에서 range함수를 사용하여 list를 생성할 수 있다.
myList = list(range(10))
arr0 = np.array(myList)
arr0

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr.shape

(10,)

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 1-1. index 지정하여 색인

#### 1차원 array

In [6]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[0]

0

In [ ]:
arr[5]

5

In [ ]:
# 10번째 리스트는 없다. 따라서 out of bounds에러가 발생
arr[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [ ]:
# 그러나 -1은 가능, -1은 뒤에서 첫번째로 이해하자.
arr[-1]

9

In [ ]:
arr[-10]

0

In [ ]:
# 뒤에서 11번째도 없다. 이것도 out of bounds에러
arr[-11]

IndexError: index -11 is out of bounds for axis 0 with size 10

#### 2차원 array

In [ ]:
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

In [ ]:
arr2d.shape

(3, 4)

arr2d[행, 열]

In [ ]:
arr2d[0, 2]

3

In [ ]:
arr2d[2, 1]

10

### 1-2. 범위 색인

#### 1차원

index 1**이상** 끝까지

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

index 5 **미만** 까지

In [ ]:
arr[:5]

array([0, 1, 2, 3, 4])

index 1이상 5미만

In [ ]:
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
arr[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

#### 2차원

In [ ]:
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

row(행)을 모두 가져오려는 경우

In [ ]:
# 0행, 모든 열
arr2d[0, :]

array([1, 2, 3, 4])

In [ ]:
arr2d[0, :].shape

(4,)

모든 행의 2열 가져오려는 경우

In [ ]:
arr2d[:, 2]

array([ 3,  7, 11])

부분 적으로 가져오려는 경우

In [ ]:
# 0,1행 모든열
arr2d[:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# 0,1행 2열부터 마지막열
arr2d[:2, 2:]

array([[3, 4],
       [7, 8]])

## 2. Fancy 인덱싱

fancy 인덱싱은 범위가 아닌 **특정 index의 집합의 값을 선택하여 추출**하고 싶을 때 활용합니다.

In [ ]:
arr = np.array([10, 23, 2, 7, 90, 65, 32, 66, 70])

반드시 **[추출하고 싶은 인덱스]** 꺾쇠 괄호로 묶어 주세요

In [ ]:
# 추출하고 싶은 인덱스를 리스트로 생성
idx = [1, 3, 5]

In [ ]:
arr[idx]

array([23,  7, 65])

변수에 지정 후 추출도 가능합니다.

### 2-2. 2차원 array

In [ ]:
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

In [ ]:
arr2d[[0, 1], :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr2d[:, [1, 2, 3]]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

## 3. Boolean 인덱싱

조건 필터링을 통하여 Boolean 값을 이용한 색인

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

### 3-1. True와 False 값으로 색인하기

In [ ]:
myTrueFalse = [True, False, True]

In [ ]:
# arr의 갯수만큼 boolean index의 리스트를 생성해줘야한다.
arr[myTrueFalse]

IndexError: ignored

In [ ]:
arr>2

array([False, False,  True,  True,  True,  True,  True])

In [ ]:
arr[arr>2]

array([3, 4, 5, 6, 7])

In [ ]:
myTrueFalse = [True, False, True, False, True, False, True]

In [ ]:
arr[myTrueFalse]

array([1, 3, 5, 7])

### 3-2. 조건필터

조건 연산자를 활용하여 필터를 생성할 수 있습니다

In [ ]:
# result에는 boolean index배열이 저장된다.
result = arr2d > 2

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

필터를 활용하여 필터에 True 조건만 색인 합니다.

이럴 때 꺾쇠 괄호로 한 번 더 묶어만 주면 됩니다. (꺾쇠 괄호 안에 조건문 삽입)

arr2d[**조건필터**]

In [9]:
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

In [ ]:
arr2d[ arr2d > 2 ]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
arr2d[ arr2d < 5 ]

array([1, 2, 3, 4])

In [19]:
result = (arr2d > 2) & (arr2d < 5)
result

array([[False, False,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [17]:
arr2d[(arr2d > 2)& (arr2d < 5)]

array([3, 4])